### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by mikerogne** [alexchiri/format-sql-alfred-workflow#2]
This works great! But is there any possibility of getting a "copy to clipboard" behavior, instead of only pasting to the active app? Sometimes I would rather, when the API sends back formatted SQL, have that formatted SQL automatically copied to clipboard (replacing unformatted SQL)... so I can paste it myself somewhere.

**Comment by alexchiri** [comment]
@mikerogne check out the version I just pushed. If you hold Cmd while hitting enter in the last step, it will only copy to clipboard. Hope it's useful and let me know how it works for you! :-)

**Comment by mikerogne** [comment]
Very kind, thanks!

**Comment by mikerogne** [comment]
Yup, this is perfect. :)
